# Generated by Django 2.0.13 on 2020-10-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
